Repository lisafuhrmann/EPWS2324-FuhrmannMehlemVonScheidt, pull requests merged in 2024-02, with the labels that each got.

#70 Tunnel Ansatz 0.4.0 [+ Rechte hinzugefügt ; + Dokumentation und Kommentare hinzugefügt]
  Rapid-Prototype/tunneling-Ansatz/index.html
  Rapid-Prototype/tunneling-Ansatz/live-cache.js
  Rapid-Prototype/tunneling-Ansatz/member-cache.js
  Rapid-Prototype/tunneling-Ansatz/package-lock.json
  Rapid-Prototype/tunneling-Ansatz/package.json
  Rapid-Prototype/tunneling-Ansatz/server.js
  Rapid-Prototype/tunneling-Ansatz/src/css/main.css
Labels: documentation, enhancement

#75 Tunneling 1.0.0 [ Audio Wiedergabe und QRCode]
  Rapid-Prototype/tunneling-Ansatz/index.html
  Rapid-Prototype/tunneling-Ansatz/live-cache.js
  Rapid-Prototype/tunneling-Ansatz/package-lock.json
  Rapid-Prototype/tunneling-Ansatz/package.json
  Rapid-Prototype/tunneling-Ansatz/server.js
  Rapid-Prototype/tunneling-Ansatz/src/audio/HyruleCastle.ogg
  Rapid-Prototype/tunneling-Ansatz/src/script/qrcode.min.js
  Rapid-Prototype/tunneling-Ansatz/src/script/video.js
Labels: enhancement

#77 Initialize application structure and setup dynamic room creation
  Main-Prototype/Custom-Solution/.gitignore
  Main-Prototype/Custom-Solution/client/.gitignore
  Main-Prototype/Custom-Solution/client/README.md
  Main-Prototype/Custom-Solution/client/package-lock.json
  Main-Prototype/Custom-Solution/client/package.json
  Main-Prototype/Custom-Solution/client/public/favicon.ico
  Main-Prototype/Custom-Solution/client/public/index.html
  Main-Prototype/Custom-Solution/client/public/logo192.png
  Main-Prototype/Custom-Solution/client/public/logo512.png
  Main-Prototype/Custom-Solution/client/public/manifest.json
  Main-Prototype/Custom-Solution/client/public/robots.txt
  Main-Prototype/Custom-Solution/client/src/App.css
  Main-Prototype/Custom-Solution/client/src/App.js
  Main-Prototype/Custom-Solution/client/src/App.test.js
  Main-Prototype/Custom-Solution/client/src/index.css
  Main-Prototype/Custom-Solution/client/src/index.js
  Main-Prototype/Custom-Solution/client/src/logo.svg
  Main-Prototype/Custom-Solution/client/src/reportWebVitals.js
  Main-Prototype/Custom-Solution/client/src/routes/CreateRoom.js
  Main-Prototype/Custom-Solution/client/src/routes/NotFound.js
  Main-Prototype/Custom-Solution/client/src/routes/Room.js
  Main-Prototype/Custom-Solution/client/src/setupTests.js
  Main-Prototype/Custom-Solution/package-lock.json
  Main-Prototype/Custom-Solution/package.json
  Main-Prototype/Custom-Solution/server.js
  Main-Prototype/main-test.js
Labels: enhancement

#81 Optimize event handling for user connections
  Main-Prototype/Custom-Solution/client/src/routes/Room.js
  Main-Prototype/Custom-Solution/server.js
Labels: enhancement

#94 Tunneling 1.1.1 [* Dateien einheitlicher benannt]
  Rapid-Prototype/tunneling-Ansatz/index.html
  Rapid-Prototype/tunneling-Ansatz/package-lock.json
  Rapid-Prototype/tunneling-Ansatz/package.json
  Rapid-Prototype/tunneling-Ansatz/src/script/media.js
Labels: documentation

#96 HotSpot 0.1.0 [* HotSpot Ansatz Code]
  Rapid-Prototype/hotspot-Ansatz/.gitignore
  Rapid-Prototype/hotspot-Ansatz/README.md
  Rapid-Prototype/hotspot-Ansatz/index.html
  Rapid-Prototype/hotspot-Ansatz/package-lock.json
  Rapid-Prototype/hotspot-Ansatz/package.json
  Rapid-Prototype/hotspot-Ansatz/public/src/script/qrcode.min.js
  Rapid-Prototype/hotspot-Ansatz/public/src/video/Polyphon_Donau-Walzer_Johann_Strauss.mp4
  Rapid-Prototype/hotspot-Ansatz/server.js
Labels: wontfix

#102 Improved video synchronization for multi-user component
  Main-Prototype/Custom-Solution/client/src/routes/Room.js
  Main-Prototype/Custom-Solution/server.js
Labels: enhancement

#101 added completed workmatrix
  Artefakte/Arbeitsmatrix_v1.0.jpg
Labels: documentation

#100 Matrix and table
  Artefakte/Bewertungsmatrix_Erfüllung_der_Anforderungen_v2.0-1.jpg
  Artefakte/Bewertungsmatrix_Erfüllung_der_Anforderungen_v2.0-2.jpg
  Artefakte/Bewertungsmatrix_Erfüllung_der_Anforderungen_v2.0-3.jpg
  Artefakte/Bewertungsmatrix_Erfüllung_der_Anforderungen_v2.0-4.jpg
  Artefakte/Bewertungsmatrix_Erfüllung_der_Anforderungen_v2.0-5.jpg
  Artefakte/Bewertungsmatrix_Erfüllung_der_Anforderungen_v2.0-6.jpg
  Artefakte/Bewertungsmatrix_Erfüllung_der_Anforderungen_v2.0-7.jpg
  Artefakte/Bewertungsmatrix_Perspektive_Entwickler_&_User_v1.0-1.jpg
  Artefakte/Bewertungsmatrix_Perspektive_Entwickler_&_User_v1.0-2.jpg
  Artefakte/Bewertungsmatrix_Perspektive_Entwickler_&_User_v1.0-3.jpg
  Artefakte/Bewertungsmatrix_Perspektive_Entwickler_&_User_v1.0-4.jpg
  Artefakte/Bewertungsmatrix_Perspektive_Entwickler_&_User_v1.0-5.jpg
  Artefakte/Vergleichstabelle_v1.0-1.jpg
  Artefakte/Vergleichstabelle_v1.0-2.jpg
Labels: documentation
